package remindme.Dialogs;

import java.awt.Image;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import javax.swing.ImageIcon;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import remindme.Entities.RemindNotification;
import remindme.Enums.ConfigKey;
import remindme.GUI.Controllers.MainController;
import remindme.Managers.SoundPlayer;
import remindme.Managers.ThemeManager;

public class ReminderDialog extends javax.swing.JDialog {

    private static final Logger logger = LoggerFactory.getLogger(ReminderDialog.class);
    private final DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("HH:mm:ss");
    private final int maxLength = 30;
    public RemindNotification remindNotification;

    public ReminderDialog(java.awt.Dialog parent, boolean modal, RemindNotification remind, boolean preview) {
        super(parent, modal);
        initComponents();
        initDialog(remind);

        ThemeManager.updateThemeDialog(this);

        // logo application
        Image icon = new ImageIcon(this.getClass().getResource(ConfigKey.LOGO_IMG.getValue())).getImage();
        this.setIconImage(icon);

        if (!preview) {
            updateRemindAfterShow(remind);
        }

        descriptionEditor.setEditable(false);
        descriptionEditor.setOpaque(false);
        descriptionEditor.setBorder(null);
    }

    private void initDialog(RemindNotification remind) {
        logger.info("Reminder opened with values: " + remind.toString());

        remindNotification = remind;

        setNameLabelText(remind.name());
        descriptionEditor.setText(remind.description());
        iconLabel.setSvgImage(remind.icon().getIconPath(), 60, 60);
        SoundPlayer.playSound(remind.sound());

        setAlwaysOnTop(remind.topLevel());

        timeLabel.setText(LocalDateTime.now().format(timeFormatter));
   }

    private static void updateRemindAfterShow(RemindNotification remind) {
        MainController.updateRemindAfterShow(remind.name());
    }

    private void setNameLabelText(String text) {
        if (text != null && text.length() > maxLength) {
            text = text.substring(0, maxLength) + "...";
        }
        nameLabel.setText(text);
    }

    @Override
    public String toString() {
        return remindNotification.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionEditor = new javax.swing.JEditorPane();
        iconLabel = new remindme.Svg.SVGLabel();
        nameLabel = new javax.swing.JLabel();
        okBtn = new javax.swing.JButton();
        timeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Remind Me");
        setResizable(false);

        // Header: icon + name with bottom separator
        iconLabel.setPreferredSize(new java.awt.Dimension(60, 60));
        iconLabel.setMinimumSize(new java.awt.Dimension(60, 60));

        nameLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 17));
        nameLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 6, 0, 0));

        javax.swing.JPanel headerInner = new javax.swing.JPanel(new java.awt.BorderLayout(8, 0));
        headerInner.setBorder(javax.swing.BorderFactory.createEmptyBorder(14, 14, 14, 14));
        headerInner.add(iconLabel, java.awt.BorderLayout.WEST);
        headerInner.add(nameLabel, java.awt.BorderLayout.CENTER);

        javax.swing.JPanel headerPanel = new javax.swing.JPanel(new java.awt.BorderLayout());
        headerPanel.add(headerInner, java.awt.BorderLayout.CENTER);
        headerPanel.add(new javax.swing.JSeparator(), java.awt.BorderLayout.SOUTH);

        // Description
        descriptionEditor.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 2, 2, 2));
        descriptionEditor.setFocusable(false);
        descriptionEditor.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(descriptionEditor);
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder());
        jScrollPane1.setPreferredSize(new java.awt.Dimension(380, 80));

        javax.swing.JPanel contentPanel = new javax.swing.JPanel(new java.awt.BorderLayout());
        contentPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(12, 14, 12, 14));
        contentPanel.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        // Footer: time label + OK button with top separator
        timeLabel.setFont(new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 11));

        okBtn.setText("Ok");
        okBtn.setPreferredSize(new java.awt.Dimension(80, 30));
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        javax.swing.JPanel footerInner = new javax.swing.JPanel(new java.awt.BorderLayout());
        footerInner.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 14, 14, 14));
        footerInner.add(timeLabel, java.awt.BorderLayout.WEST);
        footerInner.add(okBtn, java.awt.BorderLayout.EAST);

        javax.swing.JPanel footerPanel = new javax.swing.JPanel(new java.awt.BorderLayout());
        footerPanel.add(new javax.swing.JSeparator(), java.awt.BorderLayout.NORTH);
        footerPanel.add(footerInner, java.awt.BorderLayout.CENTER);

        // Assemble main layout
        getContentPane().setLayout(new java.awt.BorderLayout());
        getContentPane().add(headerPanel, java.awt.BorderLayout.NORTH);
        getContentPane().add(contentPanel, java.awt.BorderLayout.CENTER);
        getContentPane().add(footerPanel, java.awt.BorderLayout.SOUTH);

        setMinimumSize(new java.awt.Dimension(400, 200));
        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_okBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane descriptionEditor;
    private remindme.Svg.SVGLabel iconLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton okBtn;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables
}
