package remindme.Dialogs;

import java.awt.Image;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import javax.swing.ImageIcon;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import remindme.Entities.Remind;
import remindme.Entities.RemindNotification;
import remindme.Enums.ConfigKey;
import remindme.Managers.RemindManager;
import remindme.Managers.SoundPlayer;
import remindme.Managers.ThemeManager;

public class ReminderDialog extends javax.swing.JDialog {

    private static final Logger logger = LoggerFactory.getLogger(ReminderDialog.class);
    private final DateTimeFormatter timeFormatter = DateTimeFormatter.ofPattern("HH:mm:ss");
    private final int maxLength = 30;
    public RemindNotification remindNotification;

    public ReminderDialog(java.awt.Dialog parent, boolean modal, RemindNotification remind, boolean preview) {
        super(parent, modal);
        initComponents();
        initDialog(remind);

        ThemeManager.updateThemeDialog(this);

        // logo application
        Image icon = new ImageIcon(this.getClass().getResource(ConfigKey.LOGO_IMG.getValue())).getImage();
        this.setIconImage(icon);

        if (!preview) {
            updateRemindAfterShow(remind);
        }

        descriptionEditor.setEditable(false);
        descriptionEditor.setOpaque(false);
        descriptionEditor.setBorder(null);
    }

    private void initDialog(RemindNotification remind) {
        logger.info("Reminder opened with values: " + remind.toString());

        remindNotification = remind;

        setNameLabelText(remind.name());
        descriptionEditor.setText(remind.description());
        iconLabel.setSvgImage(remind.icon().getIconPath(), 50, 50);
        SoundPlayer.playSound(remind.sound());

        setAlwaysOnTop(remind.topLevel());

        timeLabel.setText(LocalDateTime.now().format(timeFormatter));
   }

    private void updateRemindAfterShow(RemindNotification remind) {
        RemindManager remindManager = new RemindManager();

        for (Remind rem : RemindManager.reminds) {
            if (remind.name().equals(rem.getName())) {
                rem.setLastExecution(LocalDateTime.now());
                rem.setRemindCount(rem.getRemindCount()+1);

                switch (rem.getExecutionMethod()) {
                    case ONE_TIME_PER_DAY -> rem.setNextExecution(LocalDateTime.of(LocalDateTime.now().toLocalDate().plusDays(1), rem.getTimeFrom()));
                    case CUSTOM_TIME_RANGE -> rem.setNextExecution(RemindManager.getNextExecutionByTimeIntervalFromSpecificTime(rem.getTimeInterval(), rem.getTimeFrom()));
                    case PC_STARTUP -> rem.setNextExecution(RemindManager.getNextExecutionByTimeInterval(rem.getTimeInterval()));
                    default -> rem.setNextExecution(LocalDateTime.of(LocalDateTime.now().toLocalDate().plusDays(1), rem.getTimeFrom()));
                }
            }
        }

        remindManager.updateRemindList();
    }

    private void setNameLabelText(String text) {
        if (text != null && text.length() > maxLength) {
            text = text.substring(0, maxLength) + "...";
        }
        nameLabel.setText(text);
    }

    @Override
    public String toString() {
        return remindNotification.toString();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionEditor = new javax.swing.JEditorPane();
        iconLabel = new remindme.Svg.SVGLabel();
        nameLabel = new javax.swing.JLabel();
        okBtn = new javax.swing.JButton();
        timeLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Remind Me");
        setResizable(false);

        descriptionEditor.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        descriptionEditor.setFocusable(false);
        descriptionEditor.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(descriptionEditor);

        nameLabel.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        nameLabel.setText("jLabel1");

        okBtn.setText("Ok");
        okBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(iconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(nameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(okBtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(iconLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(okBtn)
                    .addComponent(timeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_okBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane descriptionEditor;
    private remindme.Svg.SVGLabel iconLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton okBtn;
    private javax.swing.JLabel timeLabel;
    // End of variables declaration//GEN-END:variables
}
